### ISSUE TITLE
Comissões não são transportadas para contratos de recorrência

### ISSUE THREAD

**Issue by eduaparicio** [Escodoo/sale-addons#16]
**Descrição do erro**
Quando um pedido de venda é criado com produtos recorrentes e agentes comissionados são preenchidos nas linhas do pedido, ao confirmá-lo, o contrato gerado não considera as informações de comissão. Isso faz com que as faturas criadas automaticamente pelo contrato não carreguem as informações de comissão preenchidas no pedido de venda.

**Evidências**
Pedido de venda com comissões preenchidas:
![image](https://user-images.githubusercontent.com/6741687/92926128-f3cad880-f411-11ea-94ae-94b0bdf0e7f7.png)

Contrato gerado pelo pedido de venda sem campos para comissão
![image](https://user-images.githubusercontent.com/6741687/92926528-87040e00-f412-11ea-9deb-41593ab3cc37.png)

Fatura gerada pelo contrato com campos de comissão não preenchidos
![image](https://user-images.githubusercontent.com/6741687/92926658-bfa3e780-f412-11ea-8085-8b287d8fd353.png)

**Comment by marcelsavegnago** [comment]
@eduaparicio de fato o módulo de comissão não tem integração com o contrato. 

Para esta necessidade pode deixar que estou verificando se tem alguma iniciativa na OCA nos repositórios dos principais envolvidos com este projeto. 

Tenho localizado ou não, eu entendo podemos trabalhar em algo já alinhados com a OCA.

O que acha de propor esta funcionalidade no repositório https://github.com/oca/commission ? Consegue redigir uma Issue por lah ? Algo bem objetivo. Ou acha melhor fazer isso no repositório https://github.com/oca/contract ?
